<?php

/*
    |--------------------------------------------------------------------------
    | Variables Globales para Salud
    |--------------------------------------------------------------------------
    |
    | Descripcion de cada uno de los select usados en diversas partes del aplicativo.
    | tipoiden => incluye todos los tipos de identidad
    | tipopersona => incluye los tipos de persona segun la parte tributaria
    | regimen => identifica los tipos de regimen para IVA
    | zona => incluye los tipos de zona
    | faseaten => fases de atencion en salud, esta tambien en tabla
    | tipotarifa => los tipos de tarifa para los rips y clasificar los servicios
    | tipocon => tipo de consulta para indicadores de dcto 255
    | tipocontra => tipo de posibles contratos
    | tipotar => tipos de tarifas en un contrato o forma de contratar
    | Incluye los de la resolucion 866 del 25/jun/2021:
    |
    */
return [
    'tipoiden' => ['CC'=>'Cedula Ciudadanía',
                    'NI'=>'NIT',
                    'TI'=>'Tarjeta Identidad',
                    'RC'=>'Registro Civil',
                    'PA'=>'Pasaporte',
                    'CE'=>'Cedula Extranjería',
                    'CD'=>'Carné Diplomático',
                    'SC'=>'Salvoconducto Permanencia',
                    'PT'=>'Permiso Temporal Permanencia',
                    'PE'=>'Permiso Especial Permanencia',
                    'CN'=>'Certificado Nacido Vivo',
                    'MS'=>'Menor sin identificar',
                    'AS'=>'Adulto sin identificar',
                    'DE'=>'Documento Extranjero',
                    'SI'=>'Sin Identificación'],
    'tipopersona' => ['N'=>'Natural',
                    'J'=>'Jurídica'],
    'regimen' =>    ['S'=>'Simplificado',
                    'C'=>'Común',
                    'G'=>'Gran Contribuyente'],
    'zona' => ['R'=>'Rural',
                'U'=>'Urbana'],
    'seccion' => ['00'=>'Quirúrgico',
                '01'=>'No Quirúrgico',
                '02'=>'Comunidad',
                '03'=>'Trabajadores'],
    'faseaten'=>['01'=>'Acciones de promoción',
                '02'=>'Procedimientos preventivos',
                '03'=>'Servicio Diagnostico',
                '04'=>'Sevicio de tratamiento',
                '05'=>'Servicio de Rehabilitación'],
    'tipotarifa'=>['Q'=>'Quirurgico',
                    'N'=>'No Quirurgico',
                    'C'=>'Consulta',
                    'I'=>'Imagenologia',
                    'L'=>'Laboratorio',
                    'E'=>'Estancia',
                    'G'=>'Glucometrias',
                    'B'=>'Nebulizaciones',
                    'O'=>'Traslado',
                    'T'=>'Terapias',
                    'H'=>'Honorarios',
                    'M'=>'Materiales e Insumos',
                    'D'=>'Medicamento'],
    'tipocon'=>['I'=>'Medicina Interna',
                'P'=>'Pediatria',
                'G'=>'Ginecologia',
                'O'=>'Obstetricia',
                'C'=>'Cirugia General',
                'A'=>'No aplica'],
    'sexo1'=>['F'=>'Femenino',
            'M'=>'Masculino',
            'A'=>'Ambos'],
    'tipocontra'=>['P'=>'Paquete',
                    'E'=>'Evento',
                    'C'=>'Capitado'],
    'tipotar'=>['P'=>'Plena',
                '+'=>'Aumentar',
                '-'=>'Disminuir'],
    'sexo'=>['F'=>'Femenino',
            'M'=>'Masculino',
            'I'=>'Indeterminado'],
    'codedad'=>['A'=>'Años',
            'M'=>'Meses',
            'D'=>'Dias'],
    'area'=>['A'=>'Administración',
            'M'=>'Psicólogo',
            'E'=>'Enfermería',
            'L'=>'Logistica',
            'X'=>'Externo'],
    'estcivil'=>['CA'=>'Casada(o)',
                'SO'=>'Soltera(o)',
                'UL'=>'Unión Libre',
                'VI'=>'Viuda(o)',
                'SE'=>'Separada(o)',
                'DI'=>'Divorciada(o)'],
    'escolaridad'=>['01'=>'Preescolar',
                    '02'=>'Basica Primaria',
                    '03'=>'Basica secundaria',
                    '04'=>'Media academica',
                    '05'=>'Media tecnica',
                    '06'=>'Normalista',
                    '07'=>'Tecnica profesional',
                    '08'=>'Tecnologica',
                    '09'=>'Profesional',
                    '10'=>'Especializacion',
                    '11'=>'Maestria',
                    '12'=>'Doctorado',
                    '13'=>'Ninguno',
                    '14'=>'Sin informacion'],
    'tiposangre'=>['A+',
                    'A-',
                    'B+',
                    'B-',
                    'AB+',
                    'AB-',
                    'O+',
                    'O-'],
    'tipoafil'=>['1'=>'Cotizante',
                    '2'=>'Beneficiario',
                    '3'=>'Adicional'],
    'parentesco'=>['D'=>'Medico Tratante',
                    'I'=>'I.P.S.',
                    'F'=>'Paciente',
                    'E'=>'Esposo(A)',
                    'P'=>'Padre/Madre',
                    'R'=>'Hermano(A)',
                    'H'=>'Hijo(A)',
                    'N'=>'Nieto(A)',
                    'A'=>'Abuelo(A)',
                    'T'=>'Tio(A)',
                    'S'=>'Sobrino(A)',
                    'O'=>'Padrino/Madrina',
                    'J'=>'Ahijado(A)',
                    'V'=>'Vecino(A)',
                    'C'=>'Compañero(A)',
                    'M'=>'Amigo(A)',
                    'L'=>'Compa. Laboral'],
    'tipoelemento'=>['E'=>'Elemento',
                    'H'=>'Hoja Anexa'],
    'tipocampo'=>['M'=>'Longtext'],
    'campoelem'=>['moting'	=>	'moting',
                    'enferact'	=>	'enferact',
                    'antefam'	=>	'antefam',
                    'anteper'	=>	'anteper',
                    'alergia'	=>	'alergia',
                    'tratam'	=>	'tratam',
                    'revsist'	=>	'revsist',
                    'exafisg'	=>	'exafisg',
                    'examen'	=>	'examen',
                    'impdiaa'	=>	'impdiaa',
                    'tratamb'	=>	'tratamb',
                    'evoamb'	=>	'evoamb',
                    'trathos'	=>	'trathos',
                    'evohos'	=>	'evohos',
                    'tramedg'	=>	'tramedg',
                    'evomedg'	=>	'evomedg',
                    'apreper'	=>	'apreper',
                    'evoenfe'	=>	'evoenfe',
                    'evoterocu'	=>	'evoterocu',
                    'resum'	=>	'resum',
                    'concprof'	=>	'concprof',
                    'antepef'	=>	'antepef',
                    'valsicam'	=>	'valsicam',
                    'valsicho'	=>	'valsicho',
                    'reapoyo'	=>	'reapoyo',
                    'evsocial'	=>	'evsocial',
                    'ningre'	=>	'ningre',
                    'evohosdia'	=>	'evohosdia',
                    'laborat'	=>	'laborat',
                    'planman'	=>	'planman',
                    'planegr'	=>	'planegr'],
    'areaapli'=>['C'=>'Consulta Externa',
                'H'=>'Hospitalización',
                'G'=>'General'],
    'parencom'=>['Padre'=>'Padre',
                'Madre'=>'Madre',
                'Conyuge'=>'Conyuge',
                'Compañero(A)'=>'Compañero(A)',
                'Hermano(A)'=>'Hermano(A)',
                'Hijo(A)'=>'Hijo(A)',
                'Tio(A)'=>'Tio(A)',
                'Primo(A)'=>'Primo(A)',
                'Sobrino(A)'=>'Sobrino(A)',
                'Abuelo(A)'=>'Abuelo(A)',
                'Nieto(A)'=>'Nieto(A)',
                'Padrastro'=>'Padrastro',
                'Madrastra'=>'Madrastra',
                'Padre Adoptivo'=>'Padre Adoptivo',
                'Madre Adoptiva'=>'Madre Adoptiva',
                'Padrino/Madrina'=>'Padrino/Madrina',
                'Ahijado(A)'=>'Ahijado(A)',
                'Vecino(A)'=>'Vecino(A)',
                'Amigo(A)'=>'Amigo(A)'],
    'relacion'=>['P'=>'Positiva',
                'D'=>'Distante',
                'I'=>'Intima',
                'T'=>'Intima Conflictiva',
                'F'=>'Focalizada',
                'S'=>'Fusionada',
                'C'=>'Conflictiva',
                'E'=>'Fusionada Conflictiva',
                'R'=>'Ruptura',
                'A'=>'Abuso']










    // 'landing' => env('landing', 'Bienvenido a mi sitio'), //si son datos sensibles tómala el archivo .env. Además puedes poner un valor por defecto, como 'Bienvenido a mi sitio'.
    // 'about' => 'Sobre Nosotros', // si no es un dato sensible
    //...
];




